### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Astepmail** [sbcgua/abap_gui_boilerplate#1]
ABAPGIT activation error
3 Syntax Error for Include ZGUIBP_EXAMPLE_COMPONENT
Ty... Line Description
W 53      Include ZGUIBP EXAMPLE COMPONENT
The field "C_ACTION_TYPE" is unknown, but there is a field with the similar name
39     Program ZGUIBP_EXAMPLE
Field "C_EVENT_STATE-NEW_PAGE" is unknown. It is neither in one of the
specified tables nor defined by a "DATA" statement. "DATA" statement.
53      Include ZGUIBP_EXAMPLE_COMPONENT
The field "C_ACTION_TYPE" is unknown, but there is a field with the similar name

ABAPGIT version 1.86.0

**Comment by sbcgua** [comment]
didn't test it on a bare system, good find.
Could you pls try again, should work now.
Note that ZGUIBP_EXAMPLE_MSTSH example will not work without https://github.com/sbcgua/abap_mustache installed

**Comment by Astepmail** [comment]
Everything works, thank you
